name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Debug - List files
      run: |
        echo "=== Repository contents ==="
        ls -la
        echo "=== Package.json ==="
        cat package.json
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        echo "=== Installing dependencies ==="
        npm ci
        echo "=== Dependencies installed ==="
        
    - name: Build
      run: |
        echo "=== Building project ==="
        npm run build
        echo "=== Build completed ==="
        echo "=== Dist folder contents ==="
        ls -la dist/
        echo "=== HTML file contents ==="
        cat dist/index.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Debug - Verify artifact
      run: |
        echo "=== Artifact upload completed ==="
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Debug - Deployment info
      run: |
        echo "=== Deployment completed ==="
        echo "Page URL: ${{ steps.deployment.outputs.page_url }}"